#---------------------------------#
#      environment configuration  #
#---------------------------------#
version: 6.0.{build}.0
install:
    - git clone https://github.com/PowerShell/DscResource.Tests
    - ps: |
        $moduleName = 'xPSDesiredStateConfiguration'
        $mainModuleFolder = ".\"
        Import-Module "$env:APPVEYOR_BUILD_FOLDER\DscResource.Tests\AppVeyor.psm1"
        Invoke-AppveyorInstallTask

#---------------------------------#
#      build configuration        #
#---------------------------------#

build: false

#---------------------------------#
#      test configuration         #
#---------------------------------#

test_script:
    - ps: |
        Invoke-AppveyorTestScriptTask `
            -Type 'Default' `
            -MainModulePath $mainModuleFolder `
            -CodeCoverage `
            -CodeCovIo

#---------------------------------#
#      deployment configuration   #
#---------------------------------#

# scripts to run before deployment
deploy_script:
  - ps: |
        Invoke-AppveyorAfterTestTask `
            -MainModulePath $mainModuleFolder `
            -ResourceModuleName $moduleName
