[ClassVersion("1.0.0"),FriendlyName("xExePackage")] 
class MSFT_xExePackage : OMI_BaseResource
{
  [Key] String Name;
  [Required] String Path;
  [Write, ValueMap{"Present", "Absent"}, Values{"Present", "Absent"}] String Ensure;
  [Write] String Arguments;
  [Write, EmbeddedInstance("MSFT_Credential")] String Credential;
  [Write] UInt32 ReturnCode[];
  [Write] String FileHash;
  [Write, ValueMap{"SHA1","SHA256","SHA384","SHA512","MD5","RIPEMD160"}, Values{"SHA1","SHA256","SHA384","SHA512","MD5","RIPEMD160"}] String HashAlgorithm;
  [Write] String SignerSubject;
  [Write] String SignerThumbprint;
  [Write] String ServerCertificateValidationCallback;
  [Write] Boolean CreateCheckRegValue;
  [Write, ValueMap{"LocalMachine","CurrentUser"}, Values{"LocalMachine","CurrentUser"}] String InstalledCheckRegHive;
  [Write] String InstalledCheckRegKey;
  [Write] String InstalledCheckRegValueName;
  [Write] String InstalledCheckRegValueData;
  [Write, EmbeddedInstance("MSFT_Credential")] String RunAsCredential;
  [Read] String PackageDescription;
  [Read] String Publisher;
  [Read] String InstalledOn;
  [Read] UInt32 Size;
  [Read] String Version;
  [Read] Boolean Installed;
};
